export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE'

export const GET_ORDER_BY_ID_REQUEST = 'GET_ORDER_BY_ID_REQUEST'
export const GET_ORDER_BY_ID_SUCCESS = 'GET_ORDER_BY_ID_SUCCESS'
export const GET_ORDER_BY_ID_FAILURE = 'GET_ORDER_BY_ID_FAILURE'

export const GET_ORDER_USER_REQUEST = 'GET_ORDER_USER_REQUEST'
export const GET_ORDER_USER_SUCCESS = 'GET_ORDER_USER_SUCCESS'
export const GET_ORDER_USER_FAILURE = 'GET_ORDER_USER_FAILURE'

// Admin
export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAILURE = 'GET_ORDER_FAILURE'

export const CONFIRMED_ORDER_REQUEST = 'CONFIRMED_ORDER_REQUEST'
export const CONFIRMED_ORDER_SUCCESS = 'CONFIRMED_ORDER_SUCCESS'
export const CONFIRMED_ORDER_FAILURE = 'CONFIRMED_ORDER_FAILURE'

export const PLACED_ORDER_REQUEST = 'PLACED_ORDER_REQUEST'
export const PLACED_ORDER_SUCCESS = 'PLACED_ORDER_SUCCESS'
export const PLACED_ORDER_FAILURE = 'PLACED_ORDER_FAILURE'

export const DELIVERED_ORDER_REQUEST = 'DELIVERED_ORDER_REQUEST'
export const DELIVERED_ORDER_SUCCESS = 'DELIVERED_ORDER_SUCCESS'
export const DELIVERED_ORDER_FAILURE = 'DELIVERED_ORDER_FAILURE'

export const CANCELED_ORDER_REQUEST = 'CANCELED_ORDER_REQUEST'
export const CANCELED_ORDER_SUCCESS = 'CANCELED_ORDER_SUCCESS'
export const CANCELED_ORDER_FAILURE = 'CANCELED_ORDER_FAILURE'

export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_FAILURE = 'DELETE_ORDER_FAILURE'

export const SHIP_ORDER_REQUEST = 'SHIP_ORDER_REQUEST'
export const SHIP_ORDER_SUCCESS = 'SHIP_ORDER_SUCCESS'
export const SHIP_ORDER_FAILURE = 'SHIP_ORDER_FAILURE'
